# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    
  # Not a client, don't register with yourself
  client:  
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true 

   
     
server:
  port: 10092   # HTTP (Tomcat) port

spring:
  application:
    name: service-discovery

  # Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
#  thymeleaf:
#    enabled: false     # Disable Thymeleaf 
